name: fizz_live_pro
description: A new Flutter project for Pesu Live / Fizz Live.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0
  cupertino_icons: ^1.0.6
  # unga existing dependencies inga irukkum (zegocloud, etc.)

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - assets/
  
